name: Post diff to Discord
on:
  push:
    branches: master
env:
  DIFF: '\u001b[34m\u001b[38;5;30m     "__t\u001b[34m↵\u001b[0m\u001b[34m\u001b[38;5;30m     "__t\u001b[34m↵\u001b[0m\n\u001b[34m\u001b[38;5;30m ests__/*\u001b[34m↵\u001b[0m\u001b[34m\u001b[38;5;30m ests__/*\u001b[34m↵\u001b[0m\n\u001b[34m\u001b[38;5;30m .ts"\u001b[0m     \u001b[34m\u001b[38;5;30m .ts"\u001b[0m\n\u001b[34m\u001b[38;5;30m   ]\u001b[0m      \u001b[34m\u001b[38;5;30m   ]\u001b[0m'
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch HEAD and the commit before it
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "```ansi\n${{ env.DIFF }}```"
