name: Post diff to Discord
on:
  push:
    branches: master
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch HEAD and the commit before it
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set diff
        id: test
        run: echo "DIFF=\u001b[34m12\u001b" >> $GITHUB_OUTPUT
      - name: Get diff
        run: echo "The diff is ${{ steps.test.outputs.DIFF }}"
