name: Post diff to Discord
on:
  push:
    branches: master
jobs: 
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch HEAD and the commit before it
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get formatted diff
        id: get_diff
        uses: LikePlayingGames/line-diff-action@v1.1
        with:
          commit-hash: '@~'
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "```ansi ${{ steps.get_diff.outputs.diff }}```"