name: Post diff to Discord
on:
  push:
    branches: master
env:
  DIFF:  
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch HEAD and the commit before it
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 
      - run: find . | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"