name: Post diff to Discord
on:
  push:
    branches: master
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch HEAD and the commit before it
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set diff
        id: test
        run: echo "DIFF=[34m[38;5;30m /*.ts",[0m  [34m[38;5;30m /*.ts",[0m
[34m[38;5;30m     "__t[34m↵[0m[34m[38;5;30m     "__t[34m↵[0m
[34m[38;5;30m ests__/*[34m↵[0m[34m[38;5;30m ests__/*[34m↵[0m
[34m[38;5;30m .ts"[0m     [34m[38;5;30m .ts"[0m
[34m[38;5;30m   ][0m      [34m[38;5;30m   ][0m" >> $GITHUB_OUTPUT
      - name: Get diff
        run: echo "The diff is ${{ steps.test.outputs.DIFF }}"
