name: Post diff to Discord
on:
  push:
    branches: master
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch HEAD and the commit before it
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get formatted diff
        id: get_diff
        uses: ILikePlayingGames/line-diff-action@3ef6616
        with:
          commit-hash: '@~'
          ruler-width: '10'
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "```ansi\n${{ steps.get_diff.outputs.diff }}```"