name: Post diff to Discord
on:
  push:
    branches: master
env:
  DIFF: >-
  '[34m[38;5;30m     "__t[34m↵[0m[34m[38;5;30m     "__t[34m↵[0m\n[34m[38;5;30m ests__/*[34m↵[0m[34m[38;5;30m ests__/*[34m↵[0m\n[34m[38;5;30m .ts"[0m     [34m[38;5;30m .ts"[0m\n[34m[38;5;30m   ][0m      [34m[38;5;30m   ][0m'
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch HEAD and the commit before it
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "```ansi\n${{ env.DIFF }}```"
