name: Post diff to Discord
on:
  push:
    branches: master
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch HEAD and the commit before it
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get formatted diff
        id: diff
        uses: ILikePlayingGames/line-diff-action@3ef6616b4fbd887f75edf9b508cee0afc731d6f3
        with:
          commit-hash: '@~'
          ruler-width: '10'
      - run: echo "${{ steps.diff.outputs.diff }}"
