name: Update tracked files
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Update tracked files
        id: vars
        env:
          HYPIXEL_API_KEY: ${{ secrets.HYPIXEL_API_KEY }}
        run: |
          npm install
          npm start
          echo "$(git status --porcelain | wc -l) files | $(git status --porcelain|awk '{print "basename " $2}'| sh | sed '{:q;N;s/\n/, /g;t q}')" >> "$COMMIT_MESSAGE"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.0.0
        with:
          commit_message: ${{ env.COMMIT_MESSAGE }}
